orbs:
  terraform-orb: bankrate/terraform@1.2.0

version: 2.1

workflows:
  pipeline:
    jobs:
      - terraform-orb/init:
          name: example-with-cloudwatch-scheduled-event
          checkout: true
          save-workspace: true
          infrastructure_dir: "./examples/example-with-cloudwatch-scheduled-event"
          terraform_version: 1.0.3
          context: qa-terraform-modules-alternate-provider-testing


      - terraform-orb/init:
          name: example-with-dynamo-event
          checkout: true
          save-workspace: true
          infrastructure_dir: "./examples/example-with-dynamo-event"
          terraform_version: 1.0.3
          context: qa-terraform-modules-alternate-provider-testing


      - terraform-orb/init:
          name: example-with-functionurl
          checkout: true
          save-workspace: true
          infrastructure_dir: "./examples/example-with-functionurl"
          terraform_version: 1.0.3
          context: qa-terraform-modules-alternate-provider-testing


      - terraform-orb/init:
          name: example-with-kinesis-event
          checkout: true
          save-workspace: true
          infrastructure_dir: "./examples/example-with-kinesis-event"
          terraform_version: 1.0.3
          context: qa-terraform-modules-alternate-provider-testing


      - terraform-orb/init:
          name: example-with-s3-event
          checkout: true
          save-workspace: true
          infrastructure_dir: "./examples/example-with-s3-event"
          terraform_version: 1.0.3
          context: qa-terraform-modules-alternate-provider-testing


      - terraform-orb/init:
          name: example-with-sqs-event
          checkout: true
          save-workspace: true
          infrastructure_dir: "./examples/example-with-sqs-event"
          terraform_version: 1.0.3
          context: qa-terraform-modules-alternate-provider-testing


      - terraform-orb/init:
          name: example-with-vpc
          checkout: true
          save-workspace: true
          infrastructure_dir: "./examples/example-with-vpc"
          terraform_version: 1.0.3
          context: qa-terraform-modules-alternate-provider-testing

      # - terraform-orb/plan:
      #     name: example-without-event
      #     environment: qa
      #     infrastructure_dir: "./examples/example-without-event"
      #     terraform_version: 1.0.3
      #     attach-workspace: true
      #     save-workspace: false
      #     context: qa-terraform-modules-alternate-provider-testing
      #     requires:
      #       - tf-fmt